sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js: 6
script:
  - npm run validate
after_success:
  - npm run report-coverage
  - npm run release
